---
- name: Check if Master has initialised the cluster already
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubemasterconf_rc

- name: Creating the Cluster
  when: not kubemasterconf_rc.stat.exists
  block:
    - name: Fetch images
      ansible.builtin.command: kubeadm config images pull
      changed_when: false

    - name: Initialise the K8S cluster
      ansible.builtin.shell: |
        kubeadm init --pod-network-cidr={{ pod_nw_cidr }} --apiserver-advertise-address={{ ansible_host }}
        sleep 10
      changed_when: false

    - name: Create cluster joining script
      ansible.builtin.shell: |
        kubeadm token create --print-join-command > /srv/smbshare/join_cluster.sh
        chmod a+x /srv/smbshare/join_cluster.sh
      changed_when: false

    - name: Install CNI
      ansible.builtin.shell: |
        kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
        sleep 30
      changed_when: false

    - name: Grant kubectl access to ubuntu user
      become_user: ubuntu
      ansible.builtin.shell: |
        cd
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
        echo "alias k=kubectl" >> .bashrc
      changed_when: false
      tags: user_check
