---
- name: Check samba server config availability
  ansible.builtin.stat:
    path: "{{ smbpath }}"
  register: check_smb_file

- name: Configure smba share
  when: not check_smb_file.stat.exists
  block:
    - name: Install samba
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - samba

    - name: Create a share
      ansible.builtin.shell: |
        mkdir -p {{ smbpath }}
        chmod 777 {{ smbpath }}
      changed_when: false

    - name: Append the share details in config files
      ansible.builtin.lineinfile:
        path: /etc/samba/smb.conf
        insertafter: EOF
        line: |
          [smbshare]
          path = {{ smbpath }}
          read only = no
          guest ok = yes

    - name: Restart SMB Service
      ansible.builtin.service:
        name: smbd
        state: restarted

    - name: Grant samba share access to ubuntu user
      ansible.builtin.command: echo -e "{{ smbpasswd }}\n{{ smbpasswd }}" | sudo smbpasswd -a -s {{ smbuser }}
      changed_when: true
