---
- name: Check necessary packages
  ansible.builtin.service:
    name: containerd
    state: started
  ignore_errors: true
  register: package_rc

- name: Setup Containerd & Kubernetes basic necessary packages
  when: package_rc != 0
  block:
    - name: Downloaad Kubernetes archive keyring
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        dest: /usr/share/keyrings/kubernetes-archive-keyring.asc
        mode: '0755'

    - name: Add kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: kubernetes

    - name: Update gpg key to ASCII
      ansible.builtin.shell: |
        cd /usr/share/keyrings/
        wget https://download.docker.com/linux/ubuntu/gpg
        gpg --dearmor -o /usr/share/keyrings/docker.gpg --yes /usr/share/keyrings/gpg
        chmod a+r /usr/share/keyrings/docker.gpg
      changed_when: false

    - name: Add containerd repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable"
        state: present
        filename: docker

    - name: Install kubelet, kubeadm, kubectl, contianerd
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet
        - kubeadm
        - kubectl
        - containerd.io

    - name: Hold the installed packages
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl

# =========== containerd configuration ================
    - name: Truncate the donfig.toml file
      ansible.builtin.copy:
        content: ""
        dest: /etc/containerd/config.toml
        mode: '0644'
      changed_when: false

    - name: Configure config.toml file for systemd cgroup driver
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        insertafter: EOF
        line: |
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
