---
- name: Check the join_cluster script availability
  ansible.builtin.stat:
    path: /mnt/smbshare/join_cluster.sh
  register: file_result

- name: Descide to join the cluster
  when: file_result.stat.exists is defined and file_result.stat.exists
  block:
    - name: Join k8s cluster
      ansible.builtin.shell: |
        sh /mnt/smbshare/join_cluster.sh
        sleep 30
      changed_when: false
