---
- name: Check if nodes has joined the cluster already
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  ignore_errors: true
  register: kubeconf_info

- name: Check result
  ansible.builtin.debug:
    msg: "Node {{ ansible_host }} is {{ 'already a part of the cluster.' if kubeconf_info.stat.exists else 'not a part of the cluster.' }}"

- name: Joining the K8S Cluster
  when: not kubeconf_info.stat.exists
  block:
    - name: Check the join_cluster script availability
      ansible.builtin.stat:
        path: /tmp/join_cluster.sh
      register: file_result

    - name: Copy the cluster Joining script
      when: not file_result.stat.exists
      block:
        - name: Fetch the join_cluster script
          ansible.builtin.copy:
            src: join_cluster.sh
            dest: /tmp/join_cluster.sh
            mode: '755'

        - name: Join k8s cluster
          ansible.builtin.shell: |
            sh /tmp/join_cluster.sh
            sleep 30
          changed_when: true
