---
- name: Copy join_cluster.sh
  ansible.builtin.shell: |
    scp -p root@192.168.56.111:/tmp/join_cluster.sh /root/
    chmod +x /root/join_cluster.sh

- name: Join k8s cluster
  ansible.builtin.command: /root/join_cluster.sh
  changed_when: false
