---
- name: Check the join_cluster script availability
  ansible.builtin.stat:
    path: /mnt/smbshare/join_cluster.sh
  register: file_result

- name: Descide to join the cluster
  when: not file_result.stat.exist
  block:
    - name: Join k8s cluster
      ansible.builtin.command: /mnt/smbshare/join_cluster.sh
      changed_when: false
